export const NATIONALITIES = [
  { name: "Afghan", value: "afghan" },
  { name: "Albanian", value: "albanian" },
  { name: "Algerian", value: "algerian" },
  { name: "American", value: "american" },
  { name: "Andorran", value: "andorran" },
  { name: "Angolan", value: "angolan" },
  { name: "Antiguan or Barbudan", value: "antiguan_or_barbudan" },
  { name: "Argentine", value: "argentine" },
  { name: "Armenian", value: "armenian" },
  { name: "Australian", value: "australian" },
  { name: "Austrian", value: "austrian" },
  { name: "Azerbaijani", value: "azerbaijani" },
  { name: "Bahamian", value: "bahamian" },
  { name: "Bahraini", value: "bahraini" },
  { name: "Bangladeshi", value: "bangladeshi" },
  { name: "Barbadian", value: "barbadian" },
  { name: "Belarusian", value: "belarusian" },
  { name: "Belgian", value: "belgian" },
  { name: "Belizean", value: "belizean" },
  { name: "Beninese", value: "beninese" },
  { name: "Bhutanese", value: "bhutanese" },
  { name: "Bolivian", value: "bolivian" },
  { name: "Bosnian or Herzegovinian", value: "bosnian_or_herzegovinian" },
  { name: "Botswanan", value: "botswanan" },
  { name: "Brazilian", value: "brazilian" },
  { name: "British", value: "british" },
  { name: "Bruneian", value: "bruneian" },
  { name: "Bulgarian", value: "bulgarian" },
  { name: "Burkinabe", value: "burkinabe" },
  { name: "Burmese", value: "burmese" },
  { name: "Burundian", value: "burundian" },
  { name: "Cabo Verdean", value: "cabo_verdean" },
  { name: "Cambodian", value: "cambodian" },
  { name: "Cameroonian", value: "cameroonian" },
  { name: "Canadian", value: "canadian" },
  { name: "Central African", value: "central_african" },
  { name: "Chadian", value: "chadian" },
  { name: "Chilean", value: "chilean" },
  { name: "Chinese", value: "chinese" },
  { name: "Colombian", value: "colombian" },
  { name: "Comoran", value: "comoran" },
  { name: "Congolese (Congo)", value: "congolese_congo" },
  { name: "Congolese (DRC)", value: "congolese_drc" },
  { name: "Costa Rican", value: "costa_rican" },
  { name: "Croatian", value: "croatian" },
  { name: "Cuban", value: "cuban" },
  { name: "Cypriot", value: "cypriot" },
  { name: "Czech", value: "czech" },
  { name: "Danish", value: "danish" },
  { name: "Djiboutian", value: "djiboutian" },
  { name: "Dominican (Dominica)", value: "dominican_dominica" },
  { name: "Dominican (Dominican Republic)", value: "dominican_republic" },
  { name: "Ecuadorian", value: "ecuadorian" },
  { name: "Egyptian", value: "egyptian" },
  { name: "Emirati", value: "emirati" },
  { name: "Equatorial Guinean", value: "equatorial_guinean" },
  { name: "Eritrean", value: "eritrean" },
  { name: "Estonian", value: "estonian" },
  { name: "Eswatini", value: "eswatini" },
  { name: "Ethiopian", value: "ethiopian" },
  { name: "Fijian", value: "fijian" },
  { name: "Finnish", value: "finnish" },
  { name: "French", value: "french" },
  { name: "Gabonese", value: "gabonese" },
  { name: "Gambian", value: "gambian" },
  { name: "Georgian", value: "georgian" },
  { name: "German", value: "german" },
  { name: "Ghanaian", value: "ghanaian" },
  { name: "Greek", value: "greek" },
  { name: "Grenadian", value: "grenadian" },
  { name: "Guatemalan", value: "guatemalan" },
  { name: "Guinean", value: "guinean" },
  { name: "Guinea-Bissauan", value: "guinea_bissauan" },
  { name: "Guyanese", value: "guyanese" },
  { name: "Haitian", value: "haitian" },
  { name: "Honduran", value: "honduran" },
  { name: "Hungarian", value: "hungarian" },
  { name: "Icelandic", value: "icelandic" },
  { name: "Indian", value: "indian" },
  { name: "Indonesian", value: "indonesian" },
  { name: "Iranian", value: "iranian" },
  { name: "Iraqi", value: "iraqi" },
  { name: "Irish", value: "irish" },
  { name: "Israeli", value: "israeli" },
  { name: "Italian", value: "italian" },
  { name: "Ivorian", value: "ivorian" },
  { name: "Jamaican", value: "jamaican" },
  { name: "Japanese", value: "japanese" },
  { name: "Jordanian", value: "jordanian" },
  { name: "Kazakh", value: "kazakh" },
  { name: "Kenyan", value: "kenyan" },
  { name: "Kiribati", value: "kiribati" },
  { name: "Kosovar", value: "kosovar" },
  { name: "Kuwaiti", value: "kuwaiti" },
  { name: "Kyrgyz", value: "kyrgyz" },
  { name: "Lao", value: "lao" },
  { name: "Latvian", value: "latvian" },
  { name: "Lebanese", value: "lebanese" },
  { name: "Liberian", value: "liberian" },
  { name: "Libyan", value: "libyan" },
  { name: "Liechtensteinian", value: "liechtensteinian" },
  { name: "Lithuanian", value: "lithuanian" },
  { name: "Luxembourgish", value: "luxembourgish" },
  { name: "Malagasy", value: "malagasy" },
  { name: "Malawian", value: "malawian" },
  { name: "Malaysian", value: "malaysian" },
  { name: "Maldivian", value: "maldivian" },
  { name: "Malian", value: "malian" },
  { name: "Maltese", value: "maltese" },
  { name: "Marshallese", value: "marshallese" },
  { name: "Mauritanian", value: "mauritanian" },
  { name: "Mauritian", value: "mauritian" },
  { name: "Mexican", value: "mexican" },
  { name: "Micronesian", value: "micronesian" },
  { name: "Moldovan", value: "moldovan" },
  { name: "Monegasque", value: "monegasque" },
  { name: "Mongolian", value: "mongolian" },
  { name: "Montenegrin", value: "montenegrin" },
  { name: "Moroccan", value: "moroccan" },
  { name: "Mozambican", value: "mozambican" },
  { name: "Namibian", value: "namibian" },
  { name: "Nauruan", value: "nauruan" },
  { name: "Nepalese", value: "nepalese" },
  { name: "New Zealander", value: "new_zealander" },
  { name: "Nicaraguan", value: "nicaraguan" },
  { name: "Nigerian", value: "nigerian" },
  { name: "Nigerien", value: "nigerien" },
  { name: "North Korean", value: "north_korean" },
  { name: "Norwegian", value: "norwegian" },
  { name: "Omani", value: "omani" },
  { name: "Pakistani", value: "pakistani" },
  { name: "Palauan", value: "palauan" },
  { name: "Panamanian", value: "panamanian" },
  { name: "Papua New Guinean", value: "papua_new_guinean" },
  { name: "Paraguayan", value: "paraguayan" },
  { name: "Peruvian", value: "peruvian" },
  { name: "Polish", value: "polish" },
  { name: "Portuguese", value: "portuguese" },
  { name: "Qatari", value: "qatari" },
  { name: "Romanian", value: "romanian" },
  { name: "Russian", value: "russian" },
  { name: "Rwandan", value: "rwandan" },
  { name: "Saint Kitts and Nevis", value: "saint_kitts_and_nevis" },
  { name: "Saint Lucian", value: "saint_lucian" },
  { name: "Saint Vincentian", value: "saint_vincentian" },
  { name: "Samoan", value: "samoan" },
  { name: "San Marinese", value: "san_marinese" },
  { name: "Sao Tomean", value: "sao_tomean" },
  { name: "Saudi", value: "saudi" },
  { name: "Senegalese", value: "senegalese" },
  { name: "Serbian", value: "serbian" },
  { name: "Seychellois", value: "seychellois" },
  { name: "Sierra Leonean", value: "sierra_leonean" },
  { name: "Singaporean", value: "singaporean" },
  { name: "Slovak", value: "slovak" },
  { name: "Slovenian", value: "slovenian" },
  { name: "Solomon Islander", value: "solomon_islander" },
  { name: "Somali", value: "somali" },
  { name: "South African", value: "south_african" },
  { name: "South Korean", value: "south_korean" },
  { name: "South Sudanese", value: "south_sudanese" },
  { name: "Spanish", value: "spanish" },
  { name: "Sri Lankan", value: "sri_lankan" },
  { name: "Sudanese", value: "sudanese" },
  { name: "Surinamese", value: "surinamese" },
  { name: "Swazi", value: "swazi" },
  { name: "Swedish", value: "swedish" },
  { name: "Swiss", value: "swiss" },
  { name: "Syrian", value: "syrian" },
  { name: "Taiwanese", value: "taiwanese" },
  { name: "Tajik", value: "tajik" },
  { name: "Tanzanian", value: "tanzanian" },
  { name: "Thai", value: "thai" },
  { name: "Togolese", value: "togolese" },
  { name: "Tongan", value: "tongan" },
  { name: "Trinidadian or Tobagonian", value: "trinidadian_or_tobagonian" },
  { name: "Tunisian", value: "tunisian" },
  { name: "Turkish", value: "turkish" },
  { name: "Tuvaluan", value: "tuvaluan" },
  { name: "Ugandan", value: "ugandan" },
  { name: "Ukrainian", value: "ukrainian" },
  { name: "Uruguayan", value: "uruguayan" },
  { name: "Uzbek", value: "uzbek" },
  { name: "Vanuatu", value: "vanuatu" },
  { name: "Venezuelan", value: "venezuelan" },
  { name: "Vietnamese", value: "vietnamese" },
  { name: "Yemeni", value: "yemeni" },
  { name: "Zambian", value: "zambian" },
  { name: "Zimbabwean", value: "zimbabwean" },
];
