export const nationalities = [
  "Afghan",
  "Albanian",
  "Algerian",
  "American",
  "Andorran",
  "Angolan",
  "Antiguan or Barbudan",
  "Argentine",
  "Armenian",
  "Australian",
  "Austrian",
  "Azerbaijani",
  "Bahamian",
  "Bahraini",
  "Bangladeshi",
  "Barbadian",
  "Belarusian",
  "Belgian",
  "Belizean",
  "Beninese",
  "Bhutanese",
  "Bolivian",
  "Bosnian or Herzegovinian",
  "Botswanan",
  "Brazilian",
  "British",
  "Bruneian",
  "Bulgarian",
  "Burkinabe",
  "Burmese",
  "Burundian",
  "Cabo Verdean",
  "Cambodian",
  "Cameroonian",
  "Canadian",
  "Central African",
  "Chadian",
  "Chilean",
  "Chinese",
  "Colombian",
  "Comoran",
  "Congolese (Congo)",
  "Congolese (DRC)",
  "Costa Rican",
  "Croatian",
  "Cuban",
  "Cypriot",
  "Czech",
  "Danish",
  "Djiboutian",
  "Dominican (Dominican Republic)",
  "Dominican (Dominica)",
  "East Timorese",
  "Ecuadorian",
  "Egyptian",
  "Emirati",
  "Equatorial Guinean",
  "Eritrean",
  "Estonian",
  "Eswatini",
  "Ethiopian",
  "Fijian",
  "Finnish",
  "French",
  "Gabonese",
  "Gambian",
  "Georgian",
  "German",
  "Ghanaian",
  "Greek",
  "Grenadian",
  "Guatemalan",
  "Guinean",
  "Guinea-Bissauan",
  "Guyanese",
  "Haitian",
  "Honduran",
  "Hungarian",
  "Icelandic",
  "Indian",
  "Indonesian",
  "Iranian",
  "Iraqi",
  "Irish",
  "Israeli",
  "Italian",
  "Ivorian",
  "Jamaican",
  "Japanese",
  "Jordanian",
  "Kazakh",
  "Kenyan",
  "Kiribati",
  "North Korean",
  "South Korean",
  "Kosovar",
  "Kuwaiti",
  "Kyrgyz",
  "Lao",
  "Latvian",
  "Lebanese",
  "Liberian",
  "Libyan",
  "Liechtensteinian",
  "Lithuanian",
  "Luxembourgish",
  "Malagasy",
  "Malawian",
  "Malaysian",
  "Maldivian",
  "Malian",
  "Maltese",
  "Marshallese",
  "Mauritanian",
  "Mauritian",
  "Mexican",
  "Micronesian",
  "Moldovan",
  "Monegasque",
  "Mongolian",
  "Montenegrin",
  "Moroccan",
  "Mozambican",
  "Namibian",
  "Nauruan",
  "Nepalese",
  "Dutch",
  "New Zealander",
  "Nicaraguan",
  "Nigerian",
  "Nigerien",
  "North Macedonian",
  "Norwegian",
  "Omani",
  "Pakistani",
  "Palauan",
  "Palestinian",
  "Panamanian",
  "Papua New Guinean",
  "Paraguayan",
  "Peruvian",
  "Filipino",
  "Polish",
  "Portuguese",
  "Qatari",
  "Romanian",
  "Russian",
  "Rwandan",
  "Saint Kitts and Nevis",
  "Saint Lucian",
  "Saint Vincentian",
  "Samoan",
  "San Marinese",
  "Sao Tomean",
  "Saudi Arabian",
  "Senegalese",
  "Serbian",
  "Seychellois",
  "Sierra Leonean",
  "Singaporean",
  "Slovak",
  "Slovenian",
  "Solomon Islander",
  "Somali",
  "South African",
  "South Sudanese",
  "Spanish",
  "Sri Lankan",
  "Sudanese",
  "Surinamese",
  "Swedish",
  "Swiss",
  "Syrian",
  "Tajik",
  "Tanzanian",
  "Thai",
  "Togolese",
  "Tongan",
  "Trinidadian or Tobagonian",
  "Tunisian",
  "Turkish",
  "Turkmen",
  "Tuvaluan",
  "Ugandan",
  "Ukrainian",
  "Uruguayan",
  "Uzbek",
  "Vanuatuan",
  "Venezuelan",
  "Vietnamese",
  "Yemeni",
  "Zambian",
  "Zimbabwean"
];

export const states = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Andaman and Nicobar Islands",
  "Chandigarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Lakshadweep",
  "Puducherry",
  "Ladakh",
  "Jammu and Kashmir"
];

export const countries = [
  "United States",
  "Canada",
  "Mexico",
  "Brazil",
  "Argentina",
  "United Kingdom",
  "France",
  "Germany",
  "Italy",
  "Spain",
  "Russia",
  "China",
  "Japan",
  "South Korea",
  "India",
  "Australia",
  "New Zealand",
  "South Africa",
  "Egypt",
  "Nigeria",
  "Kenya",
  "Saudi Arabia",
  "United Arab Emirates",
  "Turkey",
  "Israel",
  "Iran",
  "Pakistan",
  "Bangladesh",
  "Indonesia",
  "Vietnam",
  "Thailand",
  "Malaysia",
  "Singapore",
  "Philippines",
  "Chile",
  "Colombia",
  "Peru",
  "Venezuela",
  "Ukraine",
  "Poland",
  "Netherlands",
  "Belgium",
  "Sweden",
  "Norway",
  "Denmark",
  "Finland",
  "Greece",
  "Portugal",
  "Austria",
  "Switzerland",
  "Ireland",
  "Czech Republic",
  "Hungary",
  "Romania",
  "Bulgaria",
  "Croatia",
  "Slovakia",
  "Slovenia",
  "Serbia",
  "Bosnia and Herzegovina",
  "North Macedonia",
  "Albania",
  "Montenegro",
  "Luxembourg",
  "Iceland",
  "Estonia",
  "Latvia",
  "Lithuania"
];

export const PAYER_TYPES = [
  {
    name: "LIC India",
    value: "LIC India",
    type: "Insurance",
    group: "Insurance",
    subGroup: "Life Insurance",
    baseTariff: "Standard"
  },
  {
    name: "Pre-employee",
    value: "Pre Employee",
    type: "Corporate",
    group: "Corporate",
    subGroup: "Pre-employment",
    baseTariff: "Premium"
  },
  {
    name: "Railway Gurgaon",
    value: "Railway Gurgaon",
    type: "PSU",
    group: "Public Sector",
    subGroup: "Railways",
    baseTariff: "Standard"
  },
  {
    name: "RAKSHA TPA PVT LTD",
    value: "RAKSHA TPA PVT LTD",
    type: "TPA",
    group: "Third Party Administrator",
    subGroup: "Private TPA",
    baseTariff: "Standard"
  },
  {
    name: "SAIL D",
    value: "SAIL D",
    type: "PSU",
    group: "Public Sector",
    subGroup: "Steel Authority",
    baseTariff: "Standard"
  },
  {
    name: "BHEL",
    value: "BHEL",
    type: "PSU",
    group: "Public Sector",
    subGroup: "Heavy Engineering",
    baseTariff: "Standard"
  },
  {
    name: "Cash",
    value: "Cash",
    type: "Cash",
    group: "Self-Pay",
    subGroup: "Direct Payment",
    baseTariff: "Discounted"
  },
  {
    name: "CM Fund",
    value: "CM Fund",
    type: "State Government",
    group: "Government Scheme",
    subGroup: "Chief Minister Fund",
    baseTariff: "Standard"
  },
  {
    name: "Arogya Sree",
    value: "Arogya Sree",
    type: "State Government",
    group: "Government Scheme",
    subGroup: "Arogya Sree",
    baseTariff: "Subsidized"
  },
  {
    name: "Delhi Government",
    value: "Delhi Government",
    type: "Delhi Government",
    group: "Government Scheme",
    subGroup: "Delhi State",
    baseTariff: "Standard"
  },
  {
    name: "District Health Centre",
    value: "District Health Centre",
    type: "PSU",
    group: "Public Sector",
    subGroup: "Health Services",
    baseTariff: "Standard"
  },
  {
    name: "Employee",
    value: "Employee",
    type: "Corporate",
    group: "Corporate",
    subGroup: "Employee Health",
    baseTariff: "Premium"
  }
];

export const INSURANCE_COMPANIES = [
  "Aditya Birla Health Insurance",
  "Aetna",
  "Ageas",
  "AIA Group",
  "Allianz",
  "American International Group (AIG)",
  "Amica Mutual",
  "Assicurazioni Generali",
  "Aviva",
  "Aviva India",
  "AXA",
  "Bajaj Allianz",
  "Bharti AXA",
  "BNP Paribas Cardif",
  "China Life Insurance",
  "Chubb",
  "Cigna",
  "Colonial Life",
  "Coventry Health Care",
  "Edelweiss Tokio",
  "Emirates Insurance Company",
  "Exide Life Insurance",
  "Farmers Insurance Group",
  "Future Generali",
  "Generali Group",
  "Great Eastern Life",
  "HDFC ERGO",
  "Hollard Group",
  "HSBC Life Insurance",
  "ICICI Lombard",
  "IFFCO Tokio",
  "Ingosstrakh",
  "Kotak Mahindra Life Insurance",
  "Legal & General",
  "Liberty Mutual",
  "LIC (Life Insurance Corporation of India)",
  "Manulife Financial",
  "MAPFRE",
  "Max Life Insurance",
  "MetLife",
  "Munich Re",
  "National Insurance Company",
  "Navi General Insurance",
  "New India Assurance",
  "Nippon Life",
  "Niva Bupa Health Insurance",
  "Oriental Insurance",
  "Pacific Life",
  "Petplan",
  "Ping An Insurance",
  "PNB MetLife",
  "Prudential Financial",
  "QBE Insurance",
  "Reliance General Insurance",
  "Reliastar Life Insurance",
  "Royal Sundaram",
  "RSA Insurance Group",
  "Samsung Life Insurance",
  "Sanlam",
  "SBI Life Insurance",
  "Securian Financial",
  "Shriram Life Insurance",
  "Star Health Insurance",
  "Sumitomo Life Insurance",
  "Suncorp Group",
  "Tata AIG",
  "The Hartford",
  "The Travelers Companies",
  "Tokio Marine",
  "Transamerica",
  "Unum",
  "UnitedHealthcare",
  "Westpac Life Insurance",
  "Zurich Insurance Group"
];

export const FAMILY_RELATIONS = [
  "Mother",
  "Father",
  "Brother",
  "Sister",
  "Uncle",
  "Aunt",
  "Cousin",
  "Mother In Law",
  "Father In Law",
  "Grandfather",
  "Grandmother",
  "Nephew",
  "Niece",
  "Son",
  "Daughter",
  "Husband",
  "Wife",
  "Friend",
  "Partner",
  "Roommate",
  "Fiancé",
  "Fiancée"
];

export const EmployeeRelations = [
  "Apprentice",
  "Board Member",
  "Consultant",
  "Contractor",
  "Director",
  "Executive",
  "Freelancer",
  "Full-Time Employee",
  "Intern",
  "Management",
  "On-Site Employee",
  "Part-Time Employee",
  "Permanent Employee",
  "Probationary Employee",
  "Remote Employee",
  "Seasonal Worker",
  "Staff",
  "Supervisor",
  "Temporary Employee",
  "Trainee",
  "Volunteer"
];

export const OCCUPATION = [
  "Doctor/Physician",
  "Nurse",
  "Pharmacist",
  "Surgeon",
  "Medical Technician",
  "Dentist",
  "Physical Therapist",
  "Occupational Therapist",
  "Radiologist",
  "Anesthesiologist",
  "Veterinarian",
  "Psychologist",
  "Psychiatrist",
  "Medical Researcher",
  "Paramedic",
  "Medical Assistant",
  "Health Information Technician",
  "Nutritionist/Dietitian",
  "Optometrist",
  "Audiologist",
  "Software Developer/Engineer",
  "IT Support Specialist",
  "System Administrator",
  "Network Engineer",
  "Database Administrator",
  "Cybersecurity Analyst",
  "Web Developer",
  "Mobile App Developer",
  "Data Scientist",
  "Machine Learning Engineer",
  "Cloud Engineer",
  "IT Project Manager",
  "DevOps Engineer",
  "UX/UI Designer",
  "IT Consultant",
  "Teacher",
  "Professor",
  "School Counselor",
  "Librarian",
  "Educational Administrator",
  "Special Education Teacher",
  "Curriculum Developer",
  "Instructional Coordinator",
  "Teaching Assistant",
  "Academic Advisor",
  "Civil Engineer",
  "Mechanical Engineer",
  "Electrical Engineer",
  "Chemical Engineer",
  "Industrial Engineer",
  "Aerospace Engineer",
  "Environmental Engineer",
  "Software Engineer",
  "Biomedical Engineer",
  "Structural Engineer",
  "Architect",
  "Landscape Architect",
  "Urban Planner",
  "Draftsman",
  "Surveyor",
  "Accountant",
  "Financial Analyst",
  "Investment Banker",
  "Marketing Manager",
  "Human Resources Manager",
  "Sales Representative",
  "Business Analyst",
  "Management Consultant",
  "Auditor",
  "Insurance Agent",
  "Real Estate Agent",
  "Loan Officer",
  "Operations Manager",
  "Entrepreneur",
  "Economist",
  "Artist",
  "Graphic Designer",
  "Actor/Actress",
  "Musician",
  "Photographer",
  "Film Director",
  "Producer",
  "Writer/Author",
  "Dancer",
  "Choreographer",
  "Animator",
  "Interior Designer",
  "Fashion Designer",
  "Art Curator",
  "Illustrator",
  "Lawyer",
  "Paralegal",
  "Judge",
  "Police Officer",
  "Firefighter",
  "Security Guard",
  "Corrections Officer",
  "Forensic Scientist",
  "Criminal Investigator",
  "Legal Secretary",
  "Biologist",
  "Chemist",
  "Physicist",
  "Geologist",
  "Environmental Scientist",
  "Research Scientist",
  "Laboratory Technician",
  "Meteorologist",
  "Astronomer",
  "Oceanographer",
  "Carpenter",
  "Electrician",
  "Plumber",
  "Welder",
  "Mason",
  "HVAC Technician",
  "Painter",
  "Roofer",
  "Heavy Equipment Operator",
  "Construction Manager",
  "Truck Driver",
  "Pilot",
  "Air Traffic Controller",
  "Ship Captain",
  "Train Conductor",
  "Logistics Manager",
  "Delivery Driver",
  "Warehouse Worker",
  "Forklift Operator",
  "Transportation Planner",
  "Hotel Manager",
  "Chef",
  "Bartender",
  "Travel Agent",
  "Tour Guide",
  "Event Planner",
  "Concierge",
  "Housekeeper",
  "Restaurant Manager",
  "Front Desk Clerk",
  "Farmer",
  "Agricultural Scientist",
  "Horticulturist",
  "Forester",
  "Fishery Manager",
  "Agricultural Engineer",
  "Agronomist",
  "Wildlife Biologist",
  "Ranch Manager",
  "Conservation Scientist",
  "Journalist",
  "Public Relations Specialist",
  "Social Media Manager",
  "Editor",
  "Copywriter",
  "Broadcaster",
  "News Anchor",
  "Translator",
  "Interpreter",
  "Communications Manager"
];

export const DISABILITIES = [
  "Alzheimer's Disease",
  "Amyotrophic Lateral Sclerosis (ALS)",
  "Anorexia Nervosa",
  "Apraxia of Speech",
  "Arthritis",
  "Autism Spectrum Disorder (ASD)",
  "Attention Deficit Hyperactivity Disorder (ADHD)",
  "Bipolar Disorder",
  "Blindness",
  "Borderline Personality Disorder",
  "Bulimia Nervosa",
  "Cancer",
  "Cataracts",
  "Chronic Fatigue Syndrome",
  "Chronic Pain",
  "Celiac Disease",
  "Cerebral Palsy",
  "Diabetes",
  "Down Syndrome",
  "Dysarthria",
  "Dyscalculia",
  "Dysgraphia",
  "Dyslexia",
  "Epilepsy",
  "Expressive Language Disorder",
  "Fetal Alcohol Spectrum Disorders",
  "Fibromyalgia",
  "Fragile X Syndrome",
  "Generalized Anxiety Disorder (GAD)",
  "Glaucoma",
  "Global Developmental Delay",
  "Guillain-Barré Syndrome",
  "Hemophilia",
  "Hemiplegia",
  "HIV/AIDS",
  "Huntington's Disease",
  "Hard of Hearing",
  "Heart Disease",
  "Hyposensitivity",
  "Hypersensitivity",
  "Intellectual Disability",
  "Lupus",
  "Learning Disabilities (Dyslexia, Dyscalculia, Dysgraphia)",
  "Low Vision",
  "Macular Degeneration",
  "Major Depressive Disorder",
  "Marfan Syndrome",
  "Meniere's Disease",
  "Multiple Sclerosis",
  "Muscular Dystrophy",
  "Narcissistic Personality Disorder",
  "Nonverbal Learning Disabilities",
  "Obsessive-Compulsive Disorder (OCD)",
  "Osteogenesis Imperfecta (Brittle Bone Disease)",
  "Panic Disorder",
  "Parkinson's Disease",
  "Paraplegia",
  "Post-Traumatic Stress Disorder (PTSD)",
  "Phenylketonuria (PKU)",
  "Quadriplegia",
  "Receptive Language Disorder",
  "Retinitis Pigmentosa",
  "Rheumatoid Arthritis",
  "Schizoaffective Disorder",
  "Schizophrenia",
  "Sensory Processing Disorder (SPD)",
  "Spina Bifida",
  "Stuttering",
  "Tourette Syndrome",
  "Tinnitus",
  "Visual Processing Disorder",
  "Wilson's Disease",
  "Cystic Fibrosis",
  "Tay-Sachs Disease",
  "Amyotrophic Lateral Sclerosis (ALS)"
];
