version: 3

tasks:
  install:
    desc: Install dependencies
    cmds:
      - pnpm install
    sources:
      - package.json
      - ../../pnpm-lock.yaml
    generates:
      - node_modules

  build:
    desc: Build the project
    cmds:
      - pnpm build
    sources:
      - src/**/*.ts
      - package.json
      - tsconfig.json
    generates:
      - dist

  lint:
    desc: Lint the project
    cmds:
      - pnpm lint
    sources:
      - src/**/*.ts
      - .eslintrc.js
      - .prettierrc
      - .prettierignore
      - package.json
      - tsconfig.json

  test:
    desc: Run the tests
    cmds:
      - pnpm test
    sources:
      - package.json
      - src/**/*.ts
      - tests/**/*.ts
      - tsconfig.json
      - vitest.config.ts

  tsc:
    desc: Run the TypeScript compiler
    cmds:
      - pnpm tsc
    sources:
      - package.json
      - src/**/*.ts
      - tsconfig.json

  parallel:
    desc: Run multiple tasks in parallel
    cmds:
      - task lint
      - task test
      - task tsc

  ci-pipeline:
    desc: Run the CI pipeline
    cmds:
      - task install
      - task parallel
      - task build

